
language: python # this works for Linux but is an error on macOS or Windows
node_js: stable
addons:
      chrome: stable
env:
  global:
    - CHROME_BIN=/usr/bin/google-chrome
jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        # need to install chrome here?
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install -r requirements.txt
  - pip3 install .

script: python3 test.py || python test.py

notifications:
  email:
    recipients:
    - pe.lacour@gmail.com
    on_failure: always




# https://help.crossbrowsertesting.com/selenium-testing/continuous-integration/travis-ci/
# https://github.com/mozilla-services/axe-selenium-python/blob/master/.travis.yml
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
# https://gist.github.com/shaypal5/7fd766933fb265af6f71a88cb91dd08c

# https://gist.github.com/chitoku-k/67068aa62aa3f077f5307ca9a822ce74
# os: osx
#node_js: '12'
#sudo: required
#env: HOMEBREW_CASK_OPTS='--appdir=/Applications'
#
#before_install:
#  - brew update > /dev/null
#  - brew cask install google-chrome

# https://github.com/peter279k/chromedriver-travis-ci/blob/master/.travis.yml

#language: node_js

#matrix:
#  include:
#    - os: linux
#      node_js: '12'
#      sudo: required
#      env: DISPLAY=':99.0'
#      dist: trusty
#      addons:
#        apt:
#          update: true
#          sources:
#            - google-chrome
#          packages:
#            - dpkg
#            - google-chrome-stable
#    - os: osx
#      node_js: '12'
#      sudo: required
#      env: HOMEBREW_CASK_OPTS='--appdir=/Applications'
#
#before_install:
#  - |
#    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#      brew update > /dev/null
#      brew cask install google-chrome
#    fi
#install:
#  - npm install
#
#before_script:
#  - |
#    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#      sh -e /etc/init.d/xvfb start
#    fi
#script:
#  - node test




# language: python
#
# sudo: true
# fast_finish: true
#
# matrix:
#   include:
#     - python: 2.7
#     - python: 3.5
#     - python: 3.6
#     - python: 3.7
#       dist: xenial
#       sudo: true
#
# install:
#   - pip install Cython
#   - pip install -r requirements.txt
#   - pip install .
#
# script:
#   - nosetests
#
# after_success:
#   - coveralls
#
# branches:
#   only:
#     - master
#
# notifications:
#   slack: tradologics:HcnS6XusfcuS02waQPCG18oc
#   webhooks:
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
#
#
#     - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
#
#     - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
#
#     - export CHROME_BIN=chromium-browser
#
#
#   addons:
#     chrome: stable
#     - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
#
#
#
#     sudo: required
#     language: python
#     node_js: stable
#     addons:
#       firefox: latest-nightly
#       chrome: stable
#
#     cache:
#       directories:
#         - $HOME/.cache/pip
#         - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
#         - node_modules
#
#     before_install:
#       - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER/chromedriver_linux64.zip
#       - mkdir $HOME/chromedriver && unzip /tmp/chromedriver.zip -d $HOME/chromedriver
#       - export PATH=$HOME/chromedriver:$PATH
#       - wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER/geckodriver-v$GECKODRIVER-linux64.tar.gz
#       - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
#       - export PATH=$HOME/geckodriver:$PATH
#       - firefox --version
#       - geckodriver --version
#     install:
#       - pip install tox
#
#     before_script:
#       - npm install
#     script: tox
#
#     jobs:
#       include:
#         - stage:
#           python: 3.6
#           env: TOXENV=py36 MOZ_HEADLESS=1 GECKODRIVER=0.23.0 CHROMEDRIVER=2.40
#         - stage:
#           python: 2.7
#           env: TOXENV=py27 MOZ_HEADLESS=1 GECKODRIVER=0.23.0 CHROMEDRIVER=2.40
#         - stage:
#           python: 3.6
#           before_install: skip
#           install: pip install tox
#           env: TOXENV=flake8
#         - stage: deploy
#           before_install: skip
#           install: skip
#           script: skip
#           skip_cleanup: true
#           deploy:
#             provider: pypi
#             user: kimberlythegeek
#             password:
#               secure: LHsL91XR32/M4r5ETAvaN/vUTakYByIfdwdCw6EI59LBvSnwaSant010QIl39+uafuev57yzUC/Y+orefczjkJnG3KdQBNS0Rt/zWIMw0Dr6Fp41Vg66e5URK/FRIwK36WlWzOcd3GkrQLLaDeqnXVzDWVMuXPP9/1ssu6mvriSeLctPsmX5N6m4yZwxNtpFsTLEh+BumXiamCuqjTI0RpyqxYlUVfio0G5LWeY9rkPskrwbSbc8xhq/PMk/ecLtlAxdn8AwgjLYCAt9d6NRfgL4Yp0R+kkfUQsX1Wf8A/pBNRr8Ht8Hy4CNlnEphgao4fgVEY4dc6tZL3FXOU9jQSmbChoANlbPzDhO+nb6d/QW5vLHVDufKyRQqtFxD90XFXlWFc/0gnD6tPZhi+UEFmBMoo9ugWDnYUeBd1T3lbwKT7sOmOQS58WhDVMLxPwr2BfgItGrNsaVHmzx9v0BnxZvD5ilmvNPrad6Rcsa0N8GtNXpnbyaupWzA97bemzuLqNHOjTm6TMZWRol6lLEJsJ1MRs7xWI4DYztXzlWITH7rvf6NNyvXKe9FPV3Lfoei3k1mT8QuEh6bIEFpBKRVV0ObQVSfFQ4M4wbgDBb3CbHVqMqFHgi98mpUo9tNGm4uzZCXw3hfEQpUPugKaH+VHoaylE+MR+fOhsyVlLQluM=
#             on:
#               tags: true
#               branch: master
#               distributions: "sdist bdist_wheel"
#               skip_cleanup: true
#
#     after_success:
#       - pip install coveralls
#       - coveralls
